"create or replace schema PUBLIC;

create or replace TABLE SNOW_ADT_FACT (
	PATIENT_ID VARCHAR(10),
	ADMIT_DATE DATE,
	ADMIT_TIME VARCHAR(5),
	DISCHARGE_DATE DATE,
	DISCHARGE_TIME VARCHAR(5),
	UNIT VARCHAR(20),
	BED_ID VARCHAR(15),
	ADMIT_REASON VARCHAR(50),
	DISCHARGE_REASON VARCHAR(30),
	ATTENDING_DOCTOR_ID VARCHAR(10),
	INSURANCE_TYPE VARCHAR(20),
	LOS_DAYS NUMBER(38,0),
	DIAGNOSIS_CODES_JSON VARIANT,
	READMISSION_FLAG NUMBER(38,0),
	PARTITION_MONTH VARCHAR(7),
	LOS_REALISTIC NUMBER(38,0)
);
create or replace TABLE SNOW_BED_MASTER (
	BED_ID VARCHAR(15),
	UNIT VARCHAR(20),
	FLOOR NUMBER(38,0),
	BED_TYPE VARCHAR(25),
	TOTAL_CAPACITY NUMBER(38,0),
	TARGET_OCC_PCT NUMBER(38,0),
	ICU_FLAG VARCHAR(3)
);
create or replace TABLE SNOW_DISCHARGE_DELAYS (
	PATIENT_ID VARCHAR(10),
	UNIT VARCHAR(20),
	EXPECTED_DISCHARGE DATE,
	ACTUAL_DISCHARGE DATE,
	DELAY_MINUTES NUMBER(38,0),
	DELAY_REASON_CODE VARCHAR(10),
	NURSE_ID VARCHAR(8),
	ESCALATED_FLAG VARCHAR(3)
);
create or replace TABLE SNOW_REVENUE_FACT (
	CLAIM_ID VARCHAR(10),
	PATIENT_ID VARCHAR(10),
	SERVICE_DATE DATE,
	SUBMISSION_DATE DATE,
	INSURANCE_TYPE VARCHAR(20),
	BILLED_AMOUNT NUMBER(10,2),
	ALLOWED_AMOUNT NUMBER(10,2),
	PAID_AMOUNT NUMBER(10,2),
	DENIAL_CODE VARCHAR(10),
	DENIAL_REASON VARCHAR(60),
	CLAIM_STATUS VARCHAR(20),
	DAYS_TO_PAYMENT NUMBER(38,0),
	PARTITION_MONTH VARCHAR(7)
);
create or replace view VW_ADT_WITH_DIAGNOSES(
	PATIENT_ID,
	ADMIT_DATE,
	DISCHARGE_DATE,
	UNIT,
	BED_ID,
	ADMIT_REASON,
	INSURANCE_TYPE,
	LOS_DAYS,
	READMISSION_FLAG,
	PARTITION_MONTH,
	DIAGNOSIS_CODE
) as
SELECT
    a.PATIENT_ID,
    a.ADMIT_DATE,
    a.DISCHARGE_DATE,
    a.UNIT,
    a.BED_ID,
    a.ADMIT_REASON,
    a.INSURANCE_TYPE,
    a.LOS_DAYS,
    a.READMISSION_FLAG,
    a.PARTITION_MONTH,
    d.value::STRING AS DIAGNOSIS_CODE
FROM SNOW_ADT_FACT a,
LATERAL FLATTEN(
    input => TRY_PARSE_JSON(a.DIAGNOSIS_CODES_JSON):codes
) d;"
